details:
  namespace: student42-bookinfo-dev
  image: ghcr.io/nattima0912/bookinfo-details
  tag: dev
  replicas: 1
  imagePullSecrets: registry-bookinfo
  port: 9080
  healthCheckPath: "/health"
ingress:
  host: bookinfo.dev.opsta.net
  path: "/student42/details(/|$)(.*)"
  serviceType: ClusterIP
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  
